### ISSUE TITLE
iavl: make nodedb/tree code more readable

### ISSUE THREAD

**Issue by ebuchman** [tendermint/merkleeyes#13]
https://github.com/tendermint/merkleeyes/pull/12#discussion_r114123709: 

It feels weird to me that the node takes the tree as an arg. I know this is how it was, but I wonder if we can remove that. eg. writePersistBytes takes the tree but doesn't seem to use it.

**Comment by zramsay** [comment]
stale. @cloudhead re-open in `/iavl` if issue still applies
