### ISSUE TITLE
Block height on proofs is wrong after restart abci app

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/merkleeyes#19]
This is a refinement of the bug reported in https://github.com/tendermint/basecoin/issues/106

Tested on master (merkleeyes v0.2.2, tendermint v0.10.0)

Shell 1:

```
rm -rf ~/.merkleeyes
merkleeyes start -d ~/.merkleeyes -l tcp://127.0.0.1:46658
```

Shell 2:

```
rm -rf ~/.tendermint
tendermint init
tendermint node
```

Shell 3:

```
sleep 300
curl http://localhost:46657/broadcast_tx_commit\?tx\=0x0101021234010177

curl http://localhost:46657/status 2>/dev/null | jq .result.latest_block_height; curl curl http://localhost:46657/abci_query\?data\=0x1234\&path\=\"/key\" 2>/dev/null | jq .result.response

# 489
{
  "code": 0,
  "index": 0,
  "key": "1234",
  "value": "77",
  "proof": "",
  "height": 490,
  "log": ""
}
```

note there is no data in the response, but it gives the height from the abci app

**Trigger problem**

Shell 1:

```
ctrl-c
merkleeyes start -d ~/.merkleeyes -l tcp://127.0.0.1:46658
```

Shell 2:

```
ctrl-c
tendermint node
```

Shell 3:

```
curl http://localhost:46657/status 2>/dev/null | jq .result.latest_block_height; curl curl http://localhost:46657/abci_query\?data\=0x1234\&path\=\"/key\" 2>/dev/null | jq .result.response

# 512
{
  "code": 0,
  "index": 0,
  "key": "1234",
  "value": "77",
  "proof": "",
  "height": 1020,
  "log": ""
} 
```

**Comment by ethanfrey** [comment]
@phomer please investigate this.  we need a fix on merkleeyes master, so we can update basecoin and have an app we can properly restart.  thank you.

**Comment by phomer** [comment]
Okay, I can fix this. The problem comes from wire serializing the struct hash and height in app.go.

It uses wire.BinaryBytes on the struct to write, then wire.ReadBinarybytes to get it back in again. If the initial height is changed from 1 to 10, the heights are wrong (no need for a restart).

**Comment by ethanfrey** [comment]
The issue is a bit deeper.

Basically, the app stores the height in the db, so it can load everything fine in a restart.  However, when it restarts, it then replays all blocks from tendermint, as if it had no db. So the height is incremented again.  I am not sure if it then executes all tx a second time, as the tx for merkleeyes are idempotent. (run set 3 times, state is the same as running once).

I think the deeper issue is how we handshake with tendermint to let it know the current height we have.  And be very careful about off by one errors here...

Also, rather than just incrementing on `Commit`, we could read the real height from `BeginBlock` or such.  I would love to see a proper fix here.

**Comment by phomer** [comment]
Yea, I am definitely seeing that :-)

**Comment by phomer** [comment]
So, on a restart merkleeyes assumes that it should continue where it left off, but tendermint wants merkleeyes to go right back to initialization. 

It looks like in your 'Trigger problem' section, if we just explicitly delete the merkleeyes db first and restart, then the two go back to being just one height apart

**Comment by phomer** [comment]
For a fix, I think when it restarts merkleeyes may get a BeginBlock with a height of 1, so if it sees this and it doesn't match its stored height, it can just wipe the database?

**Comment by phomer** [comment]
Is it possible (via fast sync?) that tendermint goes back quite a bit in height, but not to the very start again?

**Comment by ebuchman** [comment]
We should use the abci handshake. Return the correct data on Info

**Comment by phomer** [comment]
Yes, Frey and I were just talking about that :-)

**Comment by ethanfrey** [comment]
@phomer Since you have been mostly working by yourself in this repo... here's an intro into standard tendermint processes.

If you made a branch to address it, please add that branch to the issue with a link, asking for comments.

If you think you fixed it, make a pr and request a review.

Much easier to track than slack messages and makes it open to the community.

**Comment by ethanfrey** [comment]
phoemer from slack:

So I put a possible fix in the merkleeyes branch [fix-restart-height](https://github.com/tendermint/merkleeyes/tree/fix-restart-height) (it has a simple test as well). When I run against that, most of the time status and query agree on height. Occasionally, if query is run second, it can be +1. Does that sound right?

The state should be correct. I forced the state info (height, hash) to get saved in the same atomic batch of the tree itself. They are all one now

**Comment by ethanfrey** [comment]
I checked it out, compiled, and ran `height_test.sh`, seems to check out

**Comment by ethanfrey** [comment]
Did you take this into account?

https://github.com/tendermint/merkleeyes/blob/fix-restart-height/app/app.go#L43-L46

Comment doesn't match the code

**Comment by phomer** [comment]
Opps, I'll fix that :-)

**Comment by ethanfrey** [comment]
I also just pushed a fix to the scripts.

And not just change the code, do you understand why that plus 1 is there???

**Comment by ethanfrey** [comment]
Assuming there is an active network and app_hash changes each round, then we must be sure that the query proof returns the height of the header that contains the app_hash that will prove this data.

If the tx is executed in block H, the appHash resulting from this will be in block H+1.  That means, if you show me the state after executing block H, and return height H, I will get a different appHash than the proof.  We hid the +1 here rather than force any client to understand, as it seemed to make things clearer for all clients.

**Comment by ethanfrey** [comment]
Please add some tests that actually write tx, and make sure the replay state is proper.

**Comment by ethanfrey** [comment]
Pushed a change with an actual tx.  Seems to have an error on restart.

Please check out 98fdcdf05d5d4b4f02ff16aef82844a9265f0ab8

**Comment by ethanfrey** [comment]
Any progress here?  Didn't see anything pushed.

**Comment by ethanfrey** [comment]
Really would like to get a good fix into basecoin before the testnet.

**Comment by phomer** [comment]
Created a PR #20 that works for Info and preserves the behavior of Query.
