### ISSUE TITLE
not enough arguments in call to server.NewServer

### ISSUE THREAD

**Issue by arrivets** [tendermint/merkleeyes#2]
I get this error when trying to run merkleeyes:

```
~$ go get github.com/tendermint/merkleeyes/cmd/merkleeyes
# github.com/tendermint/merkleeyes/cmd/merkleeyes
gowork/src/github.com/tendermint/merkleeyes/cmd/merkleeyes/merkleeyes.go:43: not enough arguments in call to server.NewServer
```

Looking at the source code, I see that there is indeed a mismatch in the number of arguments:

In gowork/src/github.com/tendermint/merkleeyes/cmd/merkleeyes/merkleeyes.go:43:

```
...
    // Start the listener
    s, err := server.NewServer(addr, mApp)
... 
```

and in gowork/src/github.com/tendermint/tmsp/server.go:10:

```
func NewServer(protoAddr, transport string, app types.Application) (Service, error) { ...
```

**Comment by ebuchman** [comment]
yes thank you sorry, please pull latest master, should be fixed now.
