### ISSUE TITLE
The LevelDB database path gets doubled up

### ISSUE THREAD

**Issue by phomer** [tendermint/merkleeyes#23]
The apps send in a full path to the IAVL code. The underlying code passes that to the database code as two arguments: path and filename, which it concatenates for the full path. This causes the final database name to be: /fullpath/fullpath/filename.db.db. 

Example, the actual LevelDB files are found in:

/home/phomer/.basecoin_test_restart/server/data/merkleeyes.db/home/phomer/.basecoin_test_restart/server/data/merkleeyes.db.db

**Comment by ebuchman** [comment]
https://github.com/tendermint/merkleeyes/pull/29
