### ISSUE TITLE
For anyone interested in the format of the transaction

### ISSUE THREAD

**Issue by srmo** [tendermint/merkleeyes#3]
As I didn't find an obious entry point on how the data has to look like, and as I'm too new as to have concluded it by pure thought, I went through the hassle of debugging it to figure it out:

When you want to send a broadcast, you need:
`ByteType``ByteVarintSizeKey``BytesVarintKey``BytesKey``ByteVarintSizeValue``BytesVarintValue``BytesValue`
With `ByteType` one of
1. `0x01` for a set
2. `0x02` for a remove
for Check/AppendTx and one of 
1. `0x01` for 'by Key'
2. `0x02` for 'by Index'
for Query

In the end, it should have been obvious by looking at `merkleeyes/app/app.go` as it uses the generic `GetByteSlice()` from `go-wire` after switching on the initial Tx-Type byte.

I apologize, if this is documented elsewhere. Just wanted to leave this as a note for other newcomers in case they get stuck as I did :)

PS: thanks for this demonstrator app!

**Comment by ebuchman** [comment]
thanks for this. adding to readme now!
