### ISSUE TITLE
Add more proofs to IAVLTree

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/merkleeyes#30]
Currently, we have a few queries, including over ranges, but only one proof.

* This proof is a merkle proof that a given key-value pair belongs to a given root hash.

That is a good start, but there are a number of other proofs that could be useful. Here are some ideas:

* Proof of non-existence.  There is no entry for a given key.
* Proof of a range - a list of items in a range, and proof there are no missing elements.
  * First in range
  * Last in range

**Comment by cloudhead** [comment]
This is done and about to be merged in `develop`.
