### ISSUE TITLE
iavl/tests: BenchmarkImmutableAvlTreeCLevelDB crashes

### ISSUE THREAD

**Issue by odeke-em** [tendermint/merkleeyes#39]
On branch unstable, hash 25b700b87a45619cb6bd85330ab4a81b7b7fbb0d, when I went into iavl
and then ran
```shell
$ go test -v -run=^$ -bench=.
```
the code crashes with this stack trace
```shell
goos: darwin
goarch: amd64
pkg: github.com/tendermint/merkleeyes/iavl
BenchmarkImmutableAvlTreeCLevelDB-4   	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43d3645]

goroutine 13 [running]:
github.com/tendermint/tmlibs/db.NewDB(0x45200dd, 0x4, 0x45211cd, 0x8, 0x451fac7, 0x2, 0x479a2e4, 0x204059250)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tmlibs/db/db.go:55 +0x95
github.com/tendermint/merkleeyes/iavl.BenchmarkImmutableAvlTreeCLevelDB(0xc420001e00)
	/Users/emmanuelodeke/go/src/github.com/tendermint/merkleeyes/iavl/iavl_test.go:590 +0x83
testing.(*B).runN(0xc420001e00, 0x1)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/benchmark.go:141 +0xb2
testing.(*B).run1.func1(0xc420001e00)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/benchmark.go:214 +0x5a
created by testing.(*B).run1
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/benchmark.go:207 +0x80
exit status 2
FAIL	github.com/tendermint/merkleeyes/iavl	0.059s
```

Seems like this initialization
```go
db := db.NewDB("test", db.CLevelDBBackendStr, "./")
```
is trippy, or there is supposed to be a backing DB available?

**Comment by odeke-em** [comment]
Okay the problem is that some DB initializer files in there have a build tag
```
+build gcc
```
for example in https://github.com/tendermint/tmlibs/blob/2f8551d3b614dd0c0c6c114c42ab25901cc41a52/db/c_level_db.go#L1
which was the red herring, gcc as a compiler is needed for cleveldb. Seems like we need to make some documentation and clarify what's up.
/cc @ebuchman @adrianbrink

**Comment by ebuchman** [comment]
Thanks @odeke-em . I don't have much experience with c-go. Can you update the docs/makefile to fix this ?

**Comment by odeke-em** [comment]
So I've mailed https://github.com/tendermint/merkleeyes/pull/48 which adds the appropriate build tag to only run that test when the compiler they have is gcc.
