### ISSUE TITLE
add information about which hashing algorithm is used 

### ISSUE THREAD

**Issue by simonvadee** [tendermint/merkleeyes#57]
I have an ABCI application storing IAVLProofs and one has to be able to validate these proofs outside of the application's context (and independently from the merkleeyes module). The application also store different kinds of merkle trees (using some other hashing algorithm), but all of them implementing the IAVL format to store merkle proofs :
```
type IAVLProof struct {
	LeafHash   []byte
	InnerNodes []IAVLProofInnerNode
	RootHash   []byte
}

type IAVLProofInnerNode struct {
	Height int8
	Size   int
	Left   []byte
	Right  []byte
}
```
The only information missing to independently validate a proof is the hsh function used to build the IAVL tree (`ripemd160` in tendermint's case). My suggestion is to add a field `hashFunction`, either in `IAVLProofInnerNode` or directly in `IAVLProof` to make it possible for merkle proof validation systems to work with several kinds of merkle trees, including your IAVL+ implementation.

**Comment by zramsay** [comment]
Issue moved to [tendermint/iavl #11](https://github.com/tendermint/iavl/issues/11) via [**ZenHub**](https://www.zenhub.com/)
